config/routes.rb
Toy::Application.routes.draw do
  devise_for :users
  # resources :restrooms, path: 'restrooms'
  resources :restrooms do
    resources :reviews
  end

  resources :user_feedback, path: 'feedback', as: 'user_feedbacks'

  root to: 'restrooms#index'
end

app/models/restroom.rb
class Restroom < ActiveRecord::Base

  validates_presence_of :location_name
  validates_presence_of :latitude
  validates_presence_of :longitude

  has_many :reviews, dependent: :destroy,
    inverse_of: :restroom

  has_many :users, through: :reviews,
    inverse_of: :restroom

  def address
    [street_address, city, state, zip].compact.join(', ')
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  validates_presence_of :user
  validates_presence_of :restroom

  belongs_to :restroom,
    inverse_of: :reviews

  belongs_to :user,
    inverse_of: :reviews
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name

  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/ }

  has_many :reviews,
    inverse_of: :user

  has_many :restrooms, through: :reviews,
    inverse_of: :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_feedback.rb
class UserFeedback < MailForm::Base
  attribute :first_name, validate: true
  attribute :last_name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/
  attribute :subject, validate: true
  attribute :body, validate: true

  def headers
    {
      subject: "[Gotta Go] #{subject}",
      to: "ajay.vallabh@gmail.com",
      from: "#{first_name} #{last_name} - #{email}"
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end
end

app/controllers/restrooms_controller.rb
class RestroomsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create] # , :show

  def index
    @restrooms = Restroom.all
    @restroom = Restroom.new
  end

  def show
    @restroom = Restroom.find(params[:id])
  end

  def create
    @restroom = Restroom.new(restroom_params)
    if @restroom.save
      flash[:success] = 'Restroom added!'
      redirect_to root_path
    else
      flash[:alert] = 'Place a valid marker'
      redirect_to root_path
    end
  end

  protected
  def restroom_params
    params.require(:restroom).permit(:latitude, :longitude, :location_name, :street_address, :city, :state, :zip)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def index
    @restroom = Restroom.find(params[:restroom_id])
    @reviews = @restroom.reviews
  end

  def new
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @user = current_user
    @restroom = Restroom.find(params[:restroom_id])
    @review = @restroom.reviews.build(review_params)
    if @review.save
      flash[:success] = 'Review added!'
      redirect_to "/restrooms/#{@restroom.id}"
    else
      flash[:alert] = 'Enter a valid review'
      render 'new'
    end
  end

  protected
  def review_params
    params.require(:review).permit(:cleanliness, :privacy, :smell, :accessibility, :gender, :comments, :baby_station, :user_id)
  end
end

app/controllers/user_feedback_controller.rb
class UserFeedbackController < ApplicationController
  def index
    @user_feedback = UserFeedback.new
  end

  def create
    @user_feedback = UserFeedback.new(params[:user_feedback])
    @user_feedback.request = request
    if @user_feedback.deliver
      flash[:success] = 'Email sent!'
      redirect_to root_path
    else
      flash[:alert] = 'Error'
      render 'index'
    end
    # rescue ScriptError
    #   flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><%= content_for?(:title) ? yield(:title) : "Gotta Go!" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%#= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>


    <!--[if gte IE 9]>
  <style type="text/css">
    .gradient {
       filter: none;
    }
  </style>
  <![endif]-->
</head>

<body id="continue">
  <!-- BEGIN TOP NAV BAR -->
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="<%= root_path %>">Gotta Go!</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <div class="button-bar">
          <ul class="button-group right">
            <% if user_signed_in? %>
            <li class="navbuttons"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li class="menu"><%= link_to 'Sign In', new_user_session_path %></li>
            <li class="navbuttons"><%= link_to 'Sign Up', new_user_registration_path %></li>
                <!--
                <li><a href="<%#= new_user_session_path %>" class="button">Sign In</a></li>
                <li><a href="<%#= new_user_registration_path %>" class="button">Sign Up</a></li>
              -->
              <% end %>
            </ul>
          </div>
        </ul>
        <!-- Left Nav Section -->
        <!-- <ul class="left">
          <li></li>
        </ul> -->
      </section>
    </nav>
    <!-- END TOP NAV BAR -->
    <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "#{name} alert-box" %>
    <% end -%>
    <%= yield %>
     <%= javascript_include_tag "application" %>
  </body>
  </html>

app/views/restrooms/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gotta Go!</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBY3appHAkQeRQJVGwOi1p80XybQQc-BC0&sensor=true"></script>
  <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script> -->
</head>
<body>

<div class="row">
  <!-- left side -->
  <div class="small-6 columns">
    <p>&nbsp;</p>
    <h3 class="header">Click a marker to view information and reviews.</h3>
    <br/>
    <h3 class="header">Need to add a restroom?</h3>
    <% if !user_signed_in? %>
      <h6 class="subheader">Must be signed in</h6>
    <% end %>
    1) Click on the map to add a marker.<br/>
    2) Enter a location name.<br/>
    3) Add Restroom!
    <p>&nbsp;</p>
    <%= simple_form_for(@restroom) do |f| %>
    <%= f.input :location_name, label: false, placeholder: 'Location Name (50 character limit)', input_html: { maxlength: 50 } %>
    <%= f.hidden_field :latitude, readonly: true %>
    <%= f.hidden_field :longitude, readonly: true%>
    <%= f.button :submit, 'Add Restroom', class: 'button new-button' %>
    <% end %>
  </div>
  <!-- right side -->
  <div class="small-6 columns">
    <p>&nbsp;</p>
    <div id="map-canvas" class="map"></div>
  </div>
</div>
    <div class="row">
      <div class="small-6 columns">
        <%= link_to 'Feedback? Contact Me', user_feedbacks_path %>
      </div>
    </div>
</body>
</html>

app/views/restrooms/show.html.erb
<div class="row">
  <div class="small-12 columns"><h2>Location: <%= @restroom.location_name %></h2>
    <% if current_user %>
      <h4 class="subheader"><%= link_to 'Add Review', "/restrooms/#{@restroom.id}/reviews/new" %></h4>
    <% end %>
  </div>
  <div class="small-12 columns">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Posted By</th>
          <th>Date</th>
          <th>Cleanliness</th>
          <th>Privacy</th>
          <th>Smell</th>
          <th>Accessibility</th>
          <th>Gender</th>
          <th>Baby Station</th>
        </tr>
      </thead>
      <tbody>
        <% @restroom.reviews.reverse.each do |x| %>
          <tr>
            <td><%= x.user.first_name %> <%= x.user.last_name %></td>
            <td><%= x.created_at.strftime("%b %d, %Y") %></td>
            <td>
              <% if x.cleanliness.nil? %>
                <%= "N/A" %>
              <% else %>
                <%= x.cleanliness %>
              <% end %>
            </td>
            <td>
              <% if x.privacy.nil? %>
                <%= "N/A" %>
              <% else %>
                <%= x.privacy %>
              <% end %>
            </td>
            <td>
              <% if x.smell.nil? %>
                <%= "N/A" %>
              <% else %>
                <%= x.smell %>
              <% end %>
            </td>
            <td><%= x.accessibility %></td>
            <td><%= x.gender %></td>
            <td><%= x.baby_station %></td>
          </tr>
          <tr>
            <td colspan="8"><strong>Comments:</strong> <%= x.comments %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<p></p>

app/views/reviews/new.html.erb
<div class="row">
  <div class="small-3 columns"></div>
  <div class="small-6 small-centered columns">
    <h3>Add Review (1 - worst; 5 - best)</h3>
  </div>
  <div class="small-3 columns"></div>
</div>

<div class="row">
  <div class="small-3 columns"></div>
  <div class="small-6 small-centered columns"><div>
    <%= simple_form_for @review, url: url_for(action: 'create', controller: 'reviews', method: 'post') do |f| %>
    <%= f.input :cleanliness, collection: 1..5 %>
    <%= f.input :privacy, collection: 1..5 %>
    <%= f.input :smell, collection: 1..5 %>
    <%= f.input :accessibility, collection: ['Unknown', 'Public', 'Purchase Required', 'Private'], selected: 'Unknown' %>
    <%= f.input :gender, collection: ['Unisex', 'Male', 'Female', 'Both'], selected: 'Both' %>
    <%= f.input :baby_station, collection: ['Unknown', 'Yes', 'No'], selected: 'Unknown'  %>
    <%= f.input :comments, label: 'Comments (500 character limit)', as: :text, input_html: { maxlength: 500 } %>
    <%= f.hidden_field :user_id, value: current_user.id, readonly: true %>
    <%= f.button :submit, 'Add Review', class: 'button new-button' %>
    <% end %>
  </div>
  <div class="small-3 columns"></div>
</div>

<div class="row">
  <div class="small-3 columns"></div>
  <div class="small-6 small-centered columns">
    <%= link_to 'Feedback? Contact Me', user_feedbacks_path %>
  </div>
  <div class="small-3 columns"></div>
</div>

app/views/user_feedback/index.html.erb
<div class="row">
  <div class="small-3 columns"></div>
  <div class="small-6 small-centered columns">
    <h3>Contact Me</h3>
  </div>
  <div class="small-3 columns"></div>
</div>

<div class="row">
  <div class="small-3 columns"></div>
  <div class="small-6 small-centered columns"><div>
    <%= simple_form_for @user_feedback do |f| %>
    <%= f.input :first_name, label: false, placeholder: 'First Name', required: true %>
    <%= f.input :last_name, label: false, placeholder: 'Last Name', required: true %>
    <%= f.input :email, label: false, placeholder: 'Email',required: true %>
    <%= f.input :subject, label: false, placeholder: 'Subject', required: true %>
    <%= f.input :body, as: :text, label: false, placeholder: 'Body', required: true %>
    <%= f.button :submit, 'Send Message', class: 'button new-button' %>
    <% end %>
  </div>
</div>
<div class="small-3 columns"></div>
</div>